import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Chat GPT App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <header className="tesx-white bg-green-900">
        <div className="flex flex-grow">
          <Link href="/">GPT Chat</Link>
          <Link href="/about">About</Link>
        </div>
      </header>
      <div className="flex flex-col md:flex-row">
        <div className="flex-grow">
          {children}
        </div>
      </div>
      </body>
    </html>
  );
}
